name: 'WebDAV Upload Action'
description: 'Upload repository contents to WebDAV server'
inputs:
  webdav_url:
    description: 'WebDAV server URL'
    required: true
  username:
    description: 'WebDAV username'
    required: true
  password:
    description: 'WebDAV password'
    required: true
  destination_paths:
    description: 'Destination paths on WebDAV server (comma-separated, optional)'
    required: false
    default: '/'
runs:
  using: 'node20'
  main: 'dist/index.js'
